import { readFile } from "node:fs/promises";

import { describe, expect, test } from "vitest";

const packageRoot = new URL("../", import.meta.url);

async function readJson(
  relativePath: string,
): Promise<Record<string, unknown>> {
  return JSON.parse(
    await readFile(new URL(relativePath, packageRoot), "utf8"),
  ) as Record<string, unknown>;
}

describe("compiled package contract", () => {
  // "exports" is generated by tsdown (tsdown.config.ts's `exports: true`,
  // derived from its `entry` list) rather than hand-authored, and this test
  // asserts the contract independently of that config -- deriving the
  // expectation from the config it validates would pass vacuously. Bare
  // string targets (no explicit "types" condition) are the correct,
  // attw-verified shape for a pure-ESM package: TypeScript resolves the
  // sibling dist/*.d.ts implicitly (asserted to exist by
  // test/pack-inventory.test.ts). The generated manifest is committed, and
  // building twice must reproduce it byte-for-byte -- that's what lets the
  // `package` CI job's `git diff --exit-code` double as a drift gate.
  test("builds all public entry points to explicit JavaScript targets", async () => {
    const packageJson = await readJson("package.json");
    const scripts = packageJson.scripts as Record<string, string>;
    const exports = packageJson.exports as Record<string, string>;

    expect(scripts.build).toBeTypeOf("string");
    expect(exports).toEqual({
      ".": "./dist/index.js",
      "./manager": "./dist/manager.js",
      "./preset": "./dist/preset.js",
      "./preview": "./dist/preview.js",
      "./package.json": "./package.json",
    });
  });
});
